-- 코드를 작성해주세요
SELECT ID,FISH_NAME,LENGTH
FROM (SELECT F.ID, N.FISH_NAME, F.LENGTH, 
             ROW_NUMBER() OVER (PARTITION BY F.FISH_TYPE
                                ORDER BY F.LENGTH DESC) AS RN
     FROM FISH_INFO F
     JOIN FISH_NAME_INFO N
     ON F.FISH_TYPE = N.FISH_TYPE
     WHERE F.LENGTH IS NOT NULL) T
WHERE RN = 1
ORDER BY ID;