-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM (SELECT B.BOOK_ID, A.AUTHOR_NAME, B.PUBLISHED_DATE
      FROM BOOK B
      JOIN AUTHOR A
      ON B.AUTHOR_ID = A.AUTHOR_ID
      WHERE B.CATEGORY = '경제') T
ORDER BY PUBLISHED_DATE ASC;